package com.softusing.Jia.model;

import java.io.Serializable;

public class User1 implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user1.id
     *
     * @mbg.generated Tue May 16 16:23:10 JST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user1.email
     *
     * @mbg.generated Tue May 16 16:23:10 JST 2023
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user1.password
     *
     * @mbg.generated Tue May 16 16:23:10 JST 2023
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user1.phone
     *
     * @mbg.generated Tue May 16 16:23:10 JST 2023
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user1.username
     *
     * @mbg.generated Tue May 16 16:23:10 JST 2023
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user1
     *
     * @mbg.generated Tue May 16 16:23:10 JST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.id
     *
     * @return the value of user1.id
     *
     * @mbg.generated Tue May 16 16:23:10 JST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.id
     *
     * @param id the value for user1.id
     *
     * @mbg.generated Tue May 16 16:23:10 JST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.email
     *
     * @return the value of user1.email
     *
     * @mbg.generated Tue May 16 16:23:10 JST 2023
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.email
     *
     * @param email the value for user1.email
     *
     * @mbg.generated Tue May 16 16:23:10 JST 2023
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.password
     *
     * @return the value of user1.password
     *
     * @mbg.generated Tue May 16 16:23:10 JST 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.password
     *
     * @param password the value for user1.password
     *
     * @mbg.generated Tue May 16 16:23:10 JST 2023
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.phone
     *
     * @return the value of user1.phone
     *
     * @mbg.generated Tue May 16 16:23:10 JST 2023
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.phone
     *
     * @param phone the value for user1.phone
     *
     * @mbg.generated Tue May 16 16:23:10 JST 2023
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.username
     *
     * @return the value of user1.username
     *
     * @mbg.generated Tue May 16 16:23:10 JST 2023
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.username
     *
     * @param username the value for user1.username
     *
     * @mbg.generated Tue May 16 16:23:10 JST 2023
     */
    public void setUsername(String username) {
        this.username = username;
    }
}