spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaaf:
    mode: HTML
#  jpa:
#    hibernate:
#      ddlAuto: update
#    showSql: true

#debug: ture

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.softusing.Jia.model
#
#logging:
#  level:
#    root: info
#    com.lrm: debug
#  file: log/my.log
