spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaaf:
    mode: HTML

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.softusing.Jia.model
logging:
  level:
    com.learn.springboot: debug
