server:
  port: 8080
#  context-path: /api
logging:
  level:
    root: info
    com.lrm: debug
  file: logs/debug.log
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    hibernate:
      ddlAuto: update
    showSql: true