package com.softusing.Jia.mapper;

import com.softusing.Jia.model.User1;
import com.softusing.Jia.model.User1Example;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface User1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Wed May 17 11:40:25 JST 2023
     */
    long countByExample(User1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Wed May 17 11:40:25 JST 2023
     */
    int deleteByExample(User1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Wed May 17 11:40:25 JST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Wed May 17 11:40:25 JST 2023
     */
    int insert(User1 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Wed May 17 11:40:25 JST 2023
     */
    int insertSelective(User1 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Wed May 17 11:40:25 JST 2023
     */
    List<User1> selectByExample(User1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Wed May 17 11:40:25 JST 2023
     */
    User1 selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Wed May 17 11:40:25 JST 2023
     */
    int updateByExampleSelective(@Param("row") User1 row, @Param("example") User1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Wed May 17 11:40:25 JST 2023
     */
    int updateByExample(@Param("row") User1 row, @Param("example") User1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Wed May 17 11:40:25 JST 2023
     */
    int updateByPrimaryKeySelective(User1 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Wed May 17 11:40:25 JST 2023
     */
    int updateByPrimaryKey(User1 row);
}